services:
- type: web
  name: comp2068-25s-31547-lab4
  runtime: node
  repo: https://github.com/vpteruel/comp2068-25s-31547
  plan: free
  envVars:
  - key: PORT
    sync: false
  - key: NODE_ENV
    sync: false
  region: virginia
  buildCommand: pnpm install
  startCommand: node ./bin/www
  autoDeployTrigger: commit
  rootDir: lab4
version: "1"
